lsi: false
safe: true
source: [https://github.com/Valkyrie-Development/Valmatica/new/main]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
